### ISSUE TITLE
incompatible with gunicorn 19.7+

### ISSUE THREAD

**Issue by toote** [gds-operations/puppet-graphite#57]
Since version 19.7.0, gunicorn has removed the deprecated `gunicorn_django` binary. That makes the service generated by this module 100% incompatible as the service can not start due to the lack of that module.

Can be easily fixed by [pinning the `gunicorn` version in the corresponding line](https://github.com/gds-operations/puppet-graphite/blob/master/manifests/deps.pp#L16)

**Comment by issyl0** [comment]
Hi @toote! Thanks very much for this, and sorry for the delay in responding! We just got bitten by this ourselves, and after some investigation have addressed it in #59. Thanks for your pull request - sorry we didn't notice it beforehand!

**Comment by toote** [comment]
@issyl0 no problem, thanks for taking care of it!
